# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.3-openjdk-8

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn -B -Pinstallers,it.tidalwave-ci-v1,generate-revision-id
